defmodule AshCloakAutoArguments.Repo.Migrations.CreateTodos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:todos, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text)
      add(:completed, :boolean, null: false, default: false)
      add(:encrypted_some_secret, :binary)
    end
  end

  def down do
    drop(table(:todos))
  end
end
